# Generated by Django 4.2.2 on 2023-06-26 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studentmgmt_rest_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='auth0user',
            managers=[
            ],
        ),
    ]
