# Generated by Django 4.2.2 on 2023-06-26 09:24

import django.contrib.auth.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studentmgmt_rest_api', '0002_alter_auth0user_managers'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='auth0user',
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
