# Generated by Django 4.2.2 on 2023-06-26 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentmgmt_rest_api', '0003_alter_auth0user_managers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='grade',
            field=models.IntegerField(default=0),
        ),
    ]
