# Generated by Django 4.2.2 on 2023-06-11 17:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('studentmgmt_rest_api', '0003_remove_assignment_student_remove_course_instructor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='instructor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='studentmgmt_rest_api.teacher'),
        ),
    ]
