# Generated by Django 4.2.2 on 2023-06-11 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studentmgmt_rest_api', '0004_course_instructor'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='enrollment',
            unique_together={('student', 'course')},
        ),
    ]
